todo/urls.py
from django.urls import path
from todo import views

urlpatterns = [

    path('', views.home, name='home'),
    path('category/<slug:category_slug>/', views.category_name, name='category_name'),

]

todofusion/urls.py
from django.contrib import admin
from django.urls import path, include
from todo import views
from todofusion import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    # AUTH
    path('signup/', views.signup, name='signup'),
    path('login/', views.loginuser, name='loginuser'),

    # Todos
    path('current/', views.currenttodo, name='currenttodo'),
    path('done_tasks/', views.complete_tasks, name='complete_tasks'),
    path('logout/', views.logoutuser, name='logoutuser'),
    path('todocreate/', views.todocreate, name='todocreate'),
    path('todoread/<int:todo_pk>/', views.todoread, name='todoread'),
    path('todoread/<int:todo_pk>/done/', views.tododone, name='tododone'),
    path('todoread/<int:todo_pk>/delete/', views.tododelete, name='totoddelete'),
    path('', include('todo.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse





class Todo(models.Model):
    title = models.CharField(max_length=256, verbose_name='Название заметки')
    content = models.TextField(blank=True, verbose_name='Содержание')
    time_create = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    time_done = models.DateTimeField(null=True, blank=True, verbose_name='Время завершения')
    time_update = models.DateTimeField(auto_now=True, verbose_name='Время обновления')
    important = models.BooleanField(default=False, verbose_name='Важно')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey('Categories', on_delete=models.PROTECT,null=True, blank=True, verbose_name='Категория')


    def __str__(self ):
        return self.title

    class Meta:
        ordering = ['-time_create']
        indexes = [
            models.Index(fields=['-time_create'])
        ]

class Categories(models.Model):
    name = models.CharField(max_length=100, db_index=True, verbose_name='Наименование категории')
    slug = models.SlugField(max_length=255, unique=True, db_index=True)


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_name', kwargs={'category_slug': self.slug})

todo/forms.py
from django import forms
from .models import Todo, Categories


class ToDoForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Categories.objects.all(),empty_label='Выберите категорию',required=False
    )
    class Meta:
        model = Todo
        fields = ['title', 'content', 'important','category']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control','rows': 10, 'cols': 80,}),
            'important': forms.CheckboxInput(attrs={'class': 'form-check-input'}),

        }

todo/views.py
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone

from .forms import ToDoForm
from .models import Todo, Categories


# Create your views here.

def home(request):
    return render(request, 'todo/home.html')


def signup(request):
    if request.method == 'GET':
        return render(request, 'todo/signupuser.html', {'form': UserCreationForm()})

    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(request.POST['username'], password=request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('currenttodo')
            except IntegrityError:
                render(request, 'todo/signupuser.html',
                       {'form': UserCreationForm(), 'error': "That username already been taken"})
        else:
            return render(request, 'todo/signupuser.html',
                          {'form': UserCreationForm(), 'error': "Password didn't match"})


def loginuser(request):
    if request.method == 'GET':
        return render(request, 'todo/loginuser.html', {'form': AuthenticationForm()})

    else:
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'todo/loginuser.html', {'form': AuthenticationForm(), 'error': "User doesn't exist"})
        else:
            login(request, user)
            return redirect('currenttodo')


@login_required
def todoread(request, todo_pk):
    read = get_object_or_404(Todo, pk=todo_pk, user=request.user)
    form_correct = ToDoForm(instance=read)
    if request.method == "POST":
        try:
            form = ToDoForm(request.POST, instance=read)
            form.save()
            return redirect('currenttodo')
        except ValueError:
            return render(request, 'todo/todoread.html',
                          {"list_todos": read, 'correct': form_correct, 'error': 'Введены неверные данные'})

    return render(request, 'todo/todoread.html', {"list_todos": read, 'correct': form_correct})


@login_required
def complete_tasks(request):
    todos = Todo.objects.filter(user=request.user, time_done__isnull=False).order_by('-time_done')
    return render(request, 'todo/complete_tasks.html', {'todos': todos})


@login_required
def tododone(request, todo_pk):
    read_task = get_object_or_404(Todo, pk=todo_pk, user=request.user)
    if request.method == "POST":
        read_task.time_done = timezone.now()
        read_task.save()
        return redirect('currenttodo')


@login_required
def tododelete(request, todo_pk):
    read_task = get_object_or_404(Todo, pk=todo_pk, user=request.user)
    if request.method == "POST":
        read_task.delete()
        return redirect('currenttodo')


def logoutuser(request):
    if request.method == "POST":
        logout(request)
        return redirect('home')


@login_required
def todocreate(request):
    """Создание заметки"""
    if request.method == 'GET':
        return render(request, 'todo/todocreate.html', {'form': ToDoForm()})
    else:
        try:
            form = ToDoForm(request.POST)
            if form.is_valid():
                new_todo = form.save(commit=False)
                new_todo.user = request.user
                new_todo.save()
                return redirect('currenttodo')
            else:
                return (request, 'todo/todocreate.html', {'form': form})
        except ValueError:
            return render(request, 'todo/todocreate.html', {'form': ToDoForm(), 'error': 'Неверные данные'})


@login_required
def currenttodo(request):
    """При нажатии на вкладку Текущие задачи выбираются все заметки пользователя
    независимо от категории"""
    todos = Todo.objects.filter(user=request.user, time_done__isnull=True)
    notes = Todo.objects.filter(user=request.user)

    data = {
        'todos': todos,
        'notes': notes
    }
    return render(request, 'todo/currenttodo.html', data)

@login_required
def category_name(request, category_slug):
    """После выбора категории по слагу отрабатывает это представление
    в зависимости от категории и указывается выбранная категория"""
    category = get_object_or_404(Categories, slug=category_slug)
    notes = Todo.objects.filter(category=category, user=request.user)
    data = {
        'tasks': category,
        'notes': notes,
        'cat_selected': category.pk,
    }
    return render(request, 'todo/currenttodo.html', data)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Note Taking App</title>
    <link type="text/css" href="{% static 'todo/css/style.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body class="bg-light">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Note Taking App  📝</a>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'todocreate' %}">Создать заметку</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'complete_tasks' %}">Завершенные задачи</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'currenttodo' %}">Текущие задачи</a>
                </li>
                {% endif %}
            </ul>
            <div class="d-flex">
                {% if user.is_authenticated %}
                <form action="{% url 'logoutuser' %}" method="POST" class="d-inline">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Выйти</button>
                </form>
                {% else %}
                <a href="{% url 'signup' %}" class="btn btn-outline-primary me-2">Регистрация</a>
                <a href="{% url 'loginuser' %}" class="btn btn-primary">Вход</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>

<div class="container mt-4">
    <div class="bg-white rounded shadow-sm p-4">
        {% block content %}{% endblock %}
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-voPF8F21sI3ZQbtlW4wN/fi5k5jG4ozS6zv8RVcPa8VQw7X7H7lbKROJr3+eSkQd" crossorigin="anonymous"></script>
</body>
</html>

todo/templates/todo/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Note Taking App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body class="bg-light">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Note Taking App  📝</a>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'todocreate' %}">Создать заметку</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'complete_tasks' %}">Завершенные задачи</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'currenttodo' %}">Текущие задачи</a>
                </li>
                {% endif %}
            </ul>
            <div class="d-flex">
                {% if user.is_authenticated %}
                <form action="{% url 'logoutuser' %}" method="POST" class="d-inline">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Выйти</button>
                </form>
                {% else %}
                <a href="{% url 'signup' %}" class="btn btn-outline-primary me-2">Регистрация</a>
                <a href="{% url 'loginuser' %}" class="btn btn-primary">Вход</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>

<div class="container mt-4">
    <div class="bg-white rounded shadow-sm p-4">
        {% block content %}{% endblock %}
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-voPF8F21sI3ZQbtlW4wN/fi5k5jG4ozS6zv8RVcPa8VQw7X7H7lbKROJr3+eSkQd" crossorigin="anonymous"></script>
</body>
</html>

todo/templates/todo/categories.html
<ul class="list-group">
    {% for cat in cats %}
        <li class="list-group-item {% if cat.pk == cat_selected %}{% endif %}">
            <a href="{% url 'category_name' cat.slug %}">
                {{ cat.name }}
            </a>
        </li>
    {% endfor %}
</ul>

todo/templates/todo/complete_tasks.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <h1 class="mb-4">Завершенные задачи</h1>
    <div class="list-group">
        {% for todo in todos %}
        <a href="{% url 'todoread' todo.id %}" class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">
                    {% if todo.important %}
                    <strong>{{ todo.title }}</strong>
                    {% else %}
                    {{ todo.title }}
                    {% endif %}
                </h5>
                <small>{{ todo.time_done|date:'M j Y H:i' }}</small>
            </div>
            {% if todo.content %}
            <p class="mb-1">{{ todo.content }}</p>
            {% endif %}
        </a>
        {% endfor %}
    </div>
</div>
{% endblock %}

todo/templates/todo/currenttodo.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block content %}

<div class="container mt-4">

    <h2 class="mb-3">Текущие заметки: {{ tasks }}</h2>


<!-- Список категорий -->
<div class="categories-list"> {% categories cat_selected %}</div>

    <!-- Список заметок -->
    <ul class="list-group">
        {% for todo in notes %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
            <div>
                <a href="{% url 'todoread' todo.id %}" class="text-decoration-none text-dark">
                    {% if todo.important %}
                        <strong><span class="text-danger">{{ todo.title }}</span></strong>
                    {% else %}
                        {{ todo.title }}
                    {% endif %}
                    {% if todo.content %}
                        - <span class="text-muted">{{ todo.content }}</span>
                    {% endif %}
                </a>
            </div>
            {% if todo.important %}
            <span class="badge bg-danger rounded-pill">Важно</span>
            {% endif %}
        </li>
        {% endfor %}
    </ul>

</div>
{% endblock %}

todo/templates/todo/home.html
{% extends 'base.html' %}


{% block content %}
<div class="bg-white rounded shadow-sm p-4">
        {% if user.is_authenticated %}
        <div class="greeting">
            <h2>Добро пожаловать, {{ user.username }}!</h2>
            <p>Здесь вы можете создавать и управлять своими заметками.</p>
        </div>
        {% else %}
        <div class="greeting">
            <h2>Добро пожаловать в Note Taking App!</h2>
            <p>Пожалуйста, войдите или зарегистрируйтесь, чтобы начать использовать приложение.</p>
        </div>
        {% endif %}

    </div>
{% endblock %}

todo/templates/todo/loginuser.html
{% extends 'base.html' %}



{% block content %}


<h1>Login</h1>

<h2>{{ error }}</h2>
<body>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit"> Login</button>
</form>
</body>
{% endblock %}

todo/templates/todo/signupuser.html
{% extends 'base.html' %}



{% block content %}

    <title>Вход</title>
</head>
<h1>Sign Up</h1>

<h2>{{ error }}</h2>
<body>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit"> Sign Up</button>
</form>
</body>
{% endblock %}

todo/templates/todo/todocreate.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block content %}

<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card border-0 shadow-sm">
                <div class="card-body p-5">
                    <h1 class="mb-4 text-center" style="font-size: 2rem; font-weight: bold;">📝 Создать Заметку</h1>

                    {% if error %}
                        <div class="alert alert-danger" role="alert">
                            {{ error }}
                        </div>
                    {% endif %}

                    <form method="POST" class="note-form">
                        {% csrf_token %}
                        <div class="mb-3 form-floating">
                            {{ form.title|add_class:"form-control" }}
                            <label for="id_title">Название</label>
                        </div>Потяни за уголок
                        <div class="mb-3 form-floating">
                            {{ form.content|add_class:"form-control" }}
                            <label for="id_content">Содержание ✍️</label>
                        </div>
                        <div class="mb-3 form-check">
                            {{ form.important|add_class:"form-check-input" }}
                            <label class="form-check-label" for="id_important">Важно 💡</label>
                        </div>
                        <div class="mb-3 form-floating" >
                            {{ form.category|add_class:"form-select" }}
                            <label for="id_category" >Категория ️</label>
                            <option value="" selected disabled hidden>Выберите категорию</option>
                        </div>
                        <div class="d-grid">
                            <button type="submit" class="btn btn-success btn-lg">Создать</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

todo/templates/todo/todoread.html
{% extends 'base.html' %}


{% block content %}

<h1>{{ list_todos.title }}</h1>
<h2>{{ error }}</h2>
<form method="post">
        {% csrf_token %}
        {{ correct.as_p }}
    <button type="submit">Сохранить</button>
</form>

<form method="post", action="{% url 'tododone' list_todos.id %}">
        {% csrf_token %}
    <button type="submit">Завершено</button>
</form>

<form method="post", action="{% url 'totoddelete' list_todos.id %}">
        {% csrf_token %}
    <button type="submit">Удалить</button>
</form>
{% endblock %}